# Generated by Django 4.1 on 2024-10-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotograia',
            new_name='Fotografia',
        ),
    ]
